// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cenk1cenk2/plumber/v6"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandRunner creates a new instance of MockCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandRunner {
	mock := &MockCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandRunner is an autogenerated mock type for the CommandRunner type
type MockCommandRunner struct {
	mock.Mock
}

type MockCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandRunner) EXPECT() *MockCommandRunner_Expecter {
	return &MockCommandRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) Run(ctx context.Context, invocation plumber.CommandInvocation, runtime plumber.CommandRuntime) (plumber.CommandResult, error) {
	ret := _mock.Called(ctx, invocation, runtime)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 plumber.CommandResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, plumber.CommandInvocation, plumber.CommandRuntime) (plumber.CommandResult, error)); ok {
		return returnFunc(ctx, invocation, runtime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, plumber.CommandInvocation, plumber.CommandRuntime) plumber.CommandResult); ok {
		r0 = returnFunc(ctx, invocation, runtime)
	} else {
		r0 = ret.Get(0).(plumber.CommandResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, plumber.CommandInvocation, plumber.CommandRuntime) error); ok {
		r1 = returnFunc(ctx, invocation, runtime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - invocation plumber.CommandInvocation
//   - runtime plumber.CommandRuntime
func (_e *MockCommandRunner_Expecter) Run(ctx interface{}, invocation interface{}, runtime interface{}) *MockCommandRunner_Run_Call {
	return &MockCommandRunner_Run_Call{Call: _e.mock.On("Run", ctx, invocation, runtime)}
}

func (_c *MockCommandRunner_Run_Call) Run(run func(ctx context.Context, invocation plumber.CommandInvocation, runtime plumber.CommandRuntime)) *MockCommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 plumber.CommandInvocation
		if args[1] != nil {
			arg1 = args[1].(plumber.CommandInvocation)
		}
		var arg2 plumber.CommandRuntime
		if args[2] != nil {
			arg2 = args[2].(plumber.CommandRuntime)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommandRunner_Run_Call) Return(commandResult plumber.CommandResult, err error) *MockCommandRunner_Run_Call {
	_c.Call.Return(commandResult, err)
	return _c
}

func (_c *MockCommandRunner_Run_Call) RunAndReturn(run func(ctx context.Context, invocation plumber.CommandInvocation, runtime plumber.CommandRuntime) (plumber.CommandResult, error)) *MockCommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
