---
# https://taskfile.dev

version: "3"

vars: {}

env:
  CGO_ENABLED: 0
  GO_VERSION: 1.25

includes:
  go:
    taskfile: https://gitlab.kilic.dev/libraries/taskfiles/-/raw/main/Taskfile.go-library.yml?ref_type=heads
    flatten: true
